#define datAlter datAlter_v5
#define datAnnul datAnnul_v5
#define datBasic datBasic_v5
#define datCcopy datCcopy_v5
#define datCctyp datCctyp_v5
#define datCell datCell_v5
#define datChscn datChscn_v5
#define datClen datClen_v5
#define datClone datClone_v5
#define datCoerc datCoerc_v5
#define datCopy datCopy_v5
#define datDrep datDrep_v5
#define datErase datErase_v5
#define datErmsg datErmsg_v5
#define datFind datFind_v5
#define datGet datGet_v5
#define datGetC datGetC_v5
#define datGetD datGetD_v5
#define datGetI datGetI_v5
#define datGetK datGetK_v5
#define datGetW datGetW_v5
#define datGetUW datGetUW_v5
#define datGetL datGetL_v5
#define datGetR datGetR_v5
#define datGet0C datGet0C_v5
#define datGet0D datGet0D_v5
#define datGet0R datGet0R_v5
#define datGet0I datGet0I_v5
#define datGet0K datGet0K_v5
#define datGet0W datGet0W_v5
#define datGet0UW datGet0UW_v5
#define datGet0L datGet0L_v5
#define datGet1C datGet1C_v5
#define datGet1D datGet1D_v5
#define datGet1I datGet1I_v5
#define datGet1K datGet1K_v5
#define datGet1W datGet1W_v5
#define datGet1UW datGet1UW_v5
#define datGet1R datGet1R_v5
#define datGet1L datGet1L_v5
#define datGetVC datGetVC_v5
#define datGetVD datGetVD_v5
#define datGetVI datGetVI_v5
#define datGetVK datGetVK_v5
#define datGetVR datGetVR_v5
#define datGetVL datGetVL_v5
#define datIndex datIndex_v5
#define datLen datLen_v5
#define datLock datLock_v5
#define datLocked datLocked_v5
#define datMap datMap_v5
#define datMapC datMapC_v5
#define datMapD datMapD_v5
#define datMapI datMapI_v5
#define datMapK datMapK_v5
#define datMapL datMapL_v5
#define datMapR datMapR_v5
#define datMapN datMapN_v5
#define datMapV datMapV_v5
#define datMould datMould_v5
#define datMove datMove_v5
#define datMsg datMsg_v5
#define datName datName_v5
#define datNcomp datNcomp_v5
#define datNew datNew_v5
#define datNewC datNewC_v5
#define datNew0 datNew0_v5
#define datNew0D datNew0D_v5
#define datNew0I datNew0I_v5
#define datNew0K datNew0K_v5
#define datNew0W datNew0W_v5
#define datNew0UW datNew0UW_v5
#define datNew0R datNew0R_v5
#define datNew0L datNew0L_v5
#define datNew0C datNew0C_v5
#define datNew1 datNew1_v5
#define datNew1C datNew1C_v5
#define datNew1D datNew1D_v5
#define datNew1I datNew1I_v5
#define datNew1K datNew1K_v5
#define datNew1W datNew1W_v5
#define datNew1UW datNew1UW_v5
#define datNew1L datNew1L_v5
#define datNew1R datNew1R_v5
#define datParen datParen_v5
#define datPrec datPrec_v5
#define datPrim datPrim_v5
#define datPrmry datPrmry_v5
#define datPutC datPutC_v5
#define datPutD datPutD_v5
#define datPutI datPutI_v5
#define datPutK datPutK_v5
#define datPutW datPutW_v5
#define datPutUW datPutUW_v5
#define datPutR datPutR_v5
#define datPutL datPutL_v5
#define datPut datPut_v5
#define datPut0C datPut0C_v5
#define datPut0D datPut0D_v5
#define datPut0R datPut0R_v5
#define datPut0I datPut0I_v5
#define datPut0K datPut0K_v5
#define datPut0W datPut0W_v5
#define datPut0UW datPut0UW_v5
#define datPut0L datPut0L_v5
#define datPut1C datPut1C_v5
#define datPut1D datPut1D_v5
#define datPut1I datPut1I_v5
#define datPut1K datPut1K_v5
#define datPut1W datPut1W_v5
#define datPut1UW datPut1UW_v5
#define datPut1R datPut1R_v5
#define datPut1L datPut1L_v5
#define datPutVD datPutVD_v5
#define datPutVI datPutVI_v5
#define datPutVK datPutVK_v5
#define datPutVR datPutVR_v5
#define datPutVL datPutVL_v5
#define datPutVC datPutVC_v5
#define datRef datRef_v5
#define datRefct datRefct_v5
#define datRenam datRenam_v5
#define datReset datReset_v5
#define datRetyp datRetyp_v5
#define datShape datShape_v5
#define datSize datSize_v5
#define datSlice datSlice_v5
#define datState datState_v5
#define datStruc datStruc_v5
#define datTemp datTemp_v5
#define datThere datThere_v5
#define datType datType_v5
#define datNolock datNolock_v5
#define datUnlock datUnlock_v5
#define datUnmap datUnmap_v5
#define datValid datValid_v5
#define datVec datVec_v5
#define hdsCopy hdsCopy_v5
#define hdsErase hdsErase_v5
#define hdsEwild hdsEwild_v5
#define hdsFlush hdsFlush_v5
#define hdsFree hdsFree_v5
#define hdsGroup hdsGroup_v5
#define hdsGtune hdsGtune_v5
#define hdsInfoI hdsInfoI_v5
#define hdsLink hdsLink_v5
#define hdsLock hdsLock_v5
#define hdsNew hdsNew_v5
#define hdsOpen hdsOpen_v5
#define hdsShow hdsShow_v5
#define hdsState hdsState_v5
#define hdsStop hdsStop_v5
#define hdsTrace hdsTrace_v5
#define hdsTune hdsTune_v5
#define hdsWild hdsWild_v5
#define datConv datConv_v5
#define hdsClose hdsClose_v5
#define hdsFind hdsFind_v5
