/*
 * C error define file for facility SAI (210)
 * Generated by the MESSGEN utility
 */

#ifndef SAI_ERROR_DEFINED
#define SAI_ERROR_DEFINED

/* Warning */
enum { SAI__WARN            	= 148013859 };	/* messid=100 */

/* Error */
enum { SAI__ERROR           	= 148013867 };	/* messid=101 */



#endif	/* SAI_ERROR_DEFINED */
