/*
 * C error define file for facility CMP (230)
 * Generated by the MESSGEN utility
 */

#ifndef CMP_ERROR_DEFINED
#define CMP_ERROR_DEFINED

/* Type invalid */
enum { CMP__TYPIN           	= 149324579 };	/* messid=100 */

/* Dimensions invalid */
enum { CMP__DIMIN           	= 149324587 };	/* messid=101 */

/* Data currently mapped */
enum { CMP__ISMAP           	= 149324595 };	/* messid=102 */

/* Fatal internal error */
enum { CMP__FATAL           	= 149324603 };	/* messid=103 */

/* Not mapped */
enum { CMP__NOMAP           	= 149324611 };	/* messid=104 */


#endif	/* CMP_ERROR_DEFINED */
