void ary1BadD( size_t n, double *argv, int *status );
void ary1ZerD( size_t n, double *argv, int *status );
void ary1PtnD( int bad, int ndim, const hdsdim *lbnda, const hdsdim *ubnda, const double *array,const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbndd, const hdsdim *ubndd, const char *htype, HDSLoc *loc, int *dce, int *status );
void ary1Pt1D( int bad, size_t el, const double *array, const char *type, HDSLoc *loc, int *dce, int *status );
void ary1CvfD( int bad, size_t n, const double *array, const char *type, void *pntr, int *dce, int *status );
void ary1GtnD( int bad, const char *htype, HDSLoc *loc, int ndim, const hdsdim *lbndd, const hdsdim *ubndd, const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbnda, const hdsdim *ubnda, int pad, HDSLoc *scloc, double *array, int *dce, int *status );
void ary1Gt1D( int bad, HDSLoc *loc, const char *type, size_t el, int doscl, double scale, double zero, double *result, int *dce, int *status );
void ary1CvtD( int bad, size_t n, const char *type, void *pntr, double *result, int *dce, int *status );
void ary1BppD( size_t el, const double *array, int *bad, int *status );
void ary1BadF( size_t n, float *argv, int *status );
void ary1ZerF( size_t n, float *argv, int *status );
void ary1PtnF( int bad, int ndim, const hdsdim *lbnda, const hdsdim *ubnda, const float *array,const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbndd, const hdsdim *ubndd, const char *htype, HDSLoc *loc, int *dce, int *status );
void ary1Pt1F( int bad, size_t el, const float *array, const char *type, HDSLoc *loc, int *dce, int *status );
void ary1CvfF( int bad, size_t n, const float *array, const char *type, void *pntr, int *dce, int *status );
void ary1GtnF( int bad, const char *htype, HDSLoc *loc, int ndim, const hdsdim *lbndd, const hdsdim *ubndd, const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbnda, const hdsdim *ubnda, int pad, HDSLoc *scloc, float *array, int *dce, int *status );
void ary1Gt1F( int bad, HDSLoc *loc, const char *type, size_t el, int doscl, float scale, float zero, float *result, int *dce, int *status );
void ary1CvtF( int bad, size_t n, const char *type, void *pntr, float *result, int *dce, int *status );
void ary1BppF( size_t el, const float *array, int *bad, int *status );
void ary1BadI( size_t n, int *argv, int *status );
void ary1ZerI( size_t n, int *argv, int *status );
void ary1PtnI( int bad, int ndim, const hdsdim *lbnda, const hdsdim *ubnda, const int *array,const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbndd, const hdsdim *ubndd, const char *htype, HDSLoc *loc, int *dce, int *status );
void ary1Pt1I( int bad, size_t el, const int *array, const char *type, HDSLoc *loc, int *dce, int *status );
void ary1CvfI( int bad, size_t n, const int *array, const char *type, void *pntr, int *dce, int *status );
void ary1GtnI( int bad, const char *htype, HDSLoc *loc, int ndim, const hdsdim *lbndd, const hdsdim *ubndd, const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbnda, const hdsdim *ubnda, int pad, HDSLoc *scloc, int *array, int *dce, int *status );
void ary1Gt1I( int bad, HDSLoc *loc, const char *type, size_t el, int doscl, int scale, int zero, int *result, int *dce, int *status );
void ary1CvtI( int bad, size_t n, const char *type, void *pntr, int *result, int *dce, int *status );
void ary1BppI( size_t el, const int *array, int *bad, int *status );
void ary1BadW( size_t n, short int *argv, int *status );
void ary1ZerW( size_t n, short int *argv, int *status );
void ary1PtnW( int bad, int ndim, const hdsdim *lbnda, const hdsdim *ubnda, const short int *array,const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbndd, const hdsdim *ubndd, const char *htype, HDSLoc *loc, int *dce, int *status );
void ary1Pt1W( int bad, size_t el, const short int *array, const char *type, HDSLoc *loc, int *dce, int *status );
void ary1CvfW( int bad, size_t n, const short int *array, const char *type, void *pntr, int *dce, int *status );
void ary1GtnW( int bad, const char *htype, HDSLoc *loc, int ndim, const hdsdim *lbndd, const hdsdim *ubndd, const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbnda, const hdsdim *ubnda, int pad, HDSLoc *scloc, short int *array, int *dce, int *status );
void ary1Gt1W( int bad, HDSLoc *loc, const char *type, size_t el, int doscl, short int scale, short int zero, short int *result, int *dce, int *status );
void ary1CvtW( int bad, size_t n, const char *type, void *pntr, short int *result, int *dce, int *status );
void ary1BppW( size_t el, const short int *array, int *bad, int *status );
void ary1BadUW( size_t n, unsigned short int *argv, int *status );
void ary1ZerUW( size_t n, unsigned short int *argv, int *status );
void ary1PtnUW( int bad, int ndim, const hdsdim *lbnda, const hdsdim *ubnda, const unsigned short int *array,const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbndd, const hdsdim *ubndd, const char *htype, HDSLoc *loc, int *dce, int *status );
void ary1Pt1UW( int bad, size_t el, const unsigned short int *array, const char *type, HDSLoc *loc, int *dce, int *status );
void ary1CvfUW( int bad, size_t n, const unsigned short int *array, const char *type, void *pntr, int *dce, int *status );
void ary1GtnUW( int bad, const char *htype, HDSLoc *loc, int ndim, const hdsdim *lbndd, const hdsdim *ubndd, const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbnda, const hdsdim *ubnda, int pad, HDSLoc *scloc, unsigned short int *array, int *dce, int *status );
void ary1Gt1UW( int bad, HDSLoc *loc, const char *type, size_t el, int doscl, unsigned short int scale, unsigned short int zero, unsigned short int *result, int *dce, int *status );
void ary1CvtUW( int bad, size_t n, const char *type, void *pntr, unsigned short int *result, int *dce, int *status );
void ary1BppUW( size_t el, const unsigned short int *array, int *bad, int *status );
void ary1BadB( size_t n, char *argv, int *status );
void ary1ZerB( size_t n, char *argv, int *status );
void ary1PtnB( int bad, int ndim, const hdsdim *lbnda, const hdsdim *ubnda, const char *array,const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbndd, const hdsdim *ubndd, const char *htype, HDSLoc *loc, int *dce, int *status );
void ary1Pt1B( int bad, size_t el, const char *array, const char *type, HDSLoc *loc, int *dce, int *status );
void ary1CvfB( int bad, size_t n, const char *array, const char *type, void *pntr, int *dce, int *status );
void ary1GtnB( int bad, const char *htype, HDSLoc *loc, int ndim, const hdsdim *lbndd, const hdsdim *ubndd, const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbnda, const hdsdim *ubnda, int pad, HDSLoc *scloc, char *array, int *dce, int *status );
void ary1Gt1B( int bad, HDSLoc *loc, const char *type, size_t el, int doscl, char scale, char zero, char *result, int *dce, int *status );
void ary1CvtB( int bad, size_t n, const char *type, void *pntr, char *result, int *dce, int *status );
void ary1BppB( size_t el, const char *array, int *bad, int *status );
void ary1BadUB( size_t n, unsigned char *argv, int *status );
void ary1ZerUB( size_t n, unsigned char *argv, int *status );
void ary1PtnUB( int bad, int ndim, const hdsdim *lbnda, const hdsdim *ubnda, const unsigned char *array,const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbndd, const hdsdim *ubndd, const char *htype, HDSLoc *loc, int *dce, int *status );
void ary1Pt1UB( int bad, size_t el, const unsigned char *array, const char *type, HDSLoc *loc, int *dce, int *status );
void ary1CvfUB( int bad, size_t n, const unsigned char *array, const char *type, void *pntr, int *dce, int *status );
void ary1GtnUB( int bad, const char *htype, HDSLoc *loc, int ndim, const hdsdim *lbndd, const hdsdim *ubndd, const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbnda, const hdsdim *ubnda, int pad, HDSLoc *scloc, unsigned char *array, int *dce, int *status );
void ary1Gt1UB( int bad, HDSLoc *loc, const char *type, size_t el, int doscl, unsigned char scale, unsigned char zero, unsigned char *result, int *dce, int *status );
void ary1CvtUB( int bad, size_t n, const char *type, void *pntr, unsigned char *result, int *dce, int *status );
void ary1BppUB( size_t el, const unsigned char *array, int *bad, int *status );
void ary1BadK( size_t n, int64_t *argv, int *status );
void ary1ZerK( size_t n, int64_t *argv, int *status );
void ary1PtnK( int bad, int ndim, const hdsdim *lbnda, const hdsdim *ubnda, const int64_t *array,const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbndd, const hdsdim *ubndd, const char *htype, HDSLoc *loc, int *dce, int *status );
void ary1Pt1K( int bad, size_t el, const int64_t *array, const char *type, HDSLoc *loc, int *dce, int *status );
void ary1CvfK( int bad, size_t n, const int64_t *array, const char *type, void *pntr, int *dce, int *status );
void ary1GtnK( int bad, const char *htype, HDSLoc *loc, int ndim, const hdsdim *lbndd, const hdsdim *ubndd, const hdsdim *lsub, const hdsdim *usub, const hdsdim *lbnda, const hdsdim *ubnda, int pad, HDSLoc *scloc, int64_t *array, int *dce, int *status );
void ary1Gt1K( int bad, HDSLoc *loc, const char *type, size_t el, int doscl, int64_t scale, int64_t zero, int64_t *result, int *dce, int *status );
void ary1CvtK( int bad, size_t n, const char *type, void *pntr, int64_t *result, int *dce, int *status );
void ary1BppK( size_t el, const int64_t *array, int *bad, int *status );
