void vecItoD( char bad, size_t n, const int *argv, double *resv, size_t *ierr, size_t *nerr, int *status );
void vecBtoD( char bad, size_t n, const char *argv, double *resv, size_t *ierr, size_t *nerr, int *status );
void vecDtoD( char bad, size_t n, const double *argv, double *resv, size_t *ierr, size_t *nerr, int *status );
void vecKtoD( char bad, size_t n, const int64_t *argv, double *resv, size_t *ierr, size_t *nerr, int *status );
void vecFtoD( char bad, size_t n, const float *argv, double *resv, size_t *ierr, size_t *nerr, int *status );
void vecUBtoD( char bad, size_t n, const unsigned char *argv, double *resv, size_t *ierr, size_t *nerr, int *status );
void vecUWtoD( char bad, size_t n, const unsigned short int *argv, double *resv, size_t *ierr, size_t *nerr, int *status );
void vecWtoD( char bad, size_t n, const short int *argv, double *resv, size_t *ierr, size_t *nerr, int *status );
void vecItoF( char bad, size_t n, const int *argv, float *resv, size_t *ierr, size_t *nerr, int *status );
void vecBtoF( char bad, size_t n, const char *argv, float *resv, size_t *ierr, size_t *nerr, int *status );
void vecDtoF( char bad, size_t n, const double *argv, float *resv, size_t *ierr, size_t *nerr, int *status );
void vecKtoF( char bad, size_t n, const int64_t *argv, float *resv, size_t *ierr, size_t *nerr, int *status );
void vecFtoF( char bad, size_t n, const float *argv, float *resv, size_t *ierr, size_t *nerr, int *status );
void vecUBtoF( char bad, size_t n, const unsigned char *argv, float *resv, size_t *ierr, size_t *nerr, int *status );
void vecUWtoF( char bad, size_t n, const unsigned short int *argv, float *resv, size_t *ierr, size_t *nerr, int *status );
void vecWtoF( char bad, size_t n, const short int *argv, float *resv, size_t *ierr, size_t *nerr, int *status );
void vecItoI( char bad, size_t n, const int *argv, int *resv, size_t *ierr, size_t *nerr, int *status );
void vecBtoI( char bad, size_t n, const char *argv, int *resv, size_t *ierr, size_t *nerr, int *status );
void vecDtoI( char bad, size_t n, const double *argv, int *resv, size_t *ierr, size_t *nerr, int *status );
void vecKtoI( char bad, size_t n, const int64_t *argv, int *resv, size_t *ierr, size_t *nerr, int *status );
void vecFtoI( char bad, size_t n, const float *argv, int *resv, size_t *ierr, size_t *nerr, int *status );
void vecUBtoI( char bad, size_t n, const unsigned char *argv, int *resv, size_t *ierr, size_t *nerr, int *status );
void vecUWtoI( char bad, size_t n, const unsigned short int *argv, int *resv, size_t *ierr, size_t *nerr, int *status );
void vecWtoI( char bad, size_t n, const short int *argv, int *resv, size_t *ierr, size_t *nerr, int *status );
void vecItoW( char bad, size_t n, const int *argv, short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecBtoW( char bad, size_t n, const char *argv, short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecDtoW( char bad, size_t n, const double *argv, short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecKtoW( char bad, size_t n, const int64_t *argv, short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecFtoW( char bad, size_t n, const float *argv, short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecUBtoW( char bad, size_t n, const unsigned char *argv, short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecUWtoW( char bad, size_t n, const unsigned short int *argv, short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecWtoW( char bad, size_t n, const short int *argv, short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecItoUW( char bad, size_t n, const int *argv, unsigned short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecBtoUW( char bad, size_t n, const char *argv, unsigned short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecDtoUW( char bad, size_t n, const double *argv, unsigned short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecKtoUW( char bad, size_t n, const int64_t *argv, unsigned short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecFtoUW( char bad, size_t n, const float *argv, unsigned short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecUBtoUW( char bad, size_t n, const unsigned char *argv, unsigned short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecUWtoUW( char bad, size_t n, const unsigned short int *argv, unsigned short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecWtoUW( char bad, size_t n, const short int *argv, unsigned short int *resv, size_t *ierr, size_t *nerr, int *status );
void vecItoB( char bad, size_t n, const int *argv, char *resv, size_t *ierr, size_t *nerr, int *status );
void vecBtoB( char bad, size_t n, const char *argv, char *resv, size_t *ierr, size_t *nerr, int *status );
void vecDtoB( char bad, size_t n, const double *argv, char *resv, size_t *ierr, size_t *nerr, int *status );
void vecKtoB( char bad, size_t n, const int64_t *argv, char *resv, size_t *ierr, size_t *nerr, int *status );
void vecFtoB( char bad, size_t n, const float *argv, char *resv, size_t *ierr, size_t *nerr, int *status );
void vecUBtoB( char bad, size_t n, const unsigned char *argv, char *resv, size_t *ierr, size_t *nerr, int *status );
void vecUWtoB( char bad, size_t n, const unsigned short int *argv, char *resv, size_t *ierr, size_t *nerr, int *status );
void vecWtoB( char bad, size_t n, const short int *argv, char *resv, size_t *ierr, size_t *nerr, int *status );
void vecItoUB( char bad, size_t n, const int *argv, unsigned char *resv, size_t *ierr, size_t *nerr, int *status );
void vecBtoUB( char bad, size_t n, const char *argv, unsigned char *resv, size_t *ierr, size_t *nerr, int *status );
void vecDtoUB( char bad, size_t n, const double *argv, unsigned char *resv, size_t *ierr, size_t *nerr, int *status );
void vecKtoUB( char bad, size_t n, const int64_t *argv, unsigned char *resv, size_t *ierr, size_t *nerr, int *status );
void vecFtoUB( char bad, size_t n, const float *argv, unsigned char *resv, size_t *ierr, size_t *nerr, int *status );
void vecUBtoUB( char bad, size_t n, const unsigned char *argv, unsigned char *resv, size_t *ierr, size_t *nerr, int *status );
void vecUWtoUB( char bad, size_t n, const unsigned short int *argv, unsigned char *resv, size_t *ierr, size_t *nerr, int *status );
void vecWtoUB( char bad, size_t n, const short int *argv, unsigned char *resv, size_t *ierr, size_t *nerr, int *status );
void vecItoK( char bad, size_t n, const int *argv, int64_t *resv, size_t *ierr, size_t *nerr, int *status );
void vecBtoK( char bad, size_t n, const char *argv, int64_t *resv, size_t *ierr, size_t *nerr, int *status );
void vecDtoK( char bad, size_t n, const double *argv, int64_t *resv, size_t *ierr, size_t *nerr, int *status );
void vecKtoK( char bad, size_t n, const int64_t *argv, int64_t *resv, size_t *ierr, size_t *nerr, int *status );
void vecFtoK( char bad, size_t n, const float *argv, int64_t *resv, size_t *ierr, size_t *nerr, int *status );
void vecUBtoK( char bad, size_t n, const unsigned char *argv, int64_t *resv, size_t *ierr, size_t *nerr, int *status );
void vecUWtoK( char bad, size_t n, const unsigned short int *argv, int64_t *resv, size_t *ierr, size_t *nerr, int *status );
void vecWtoK( char bad, size_t n, const short int *argv, int64_t *resv, size_t *ierr, size_t *nerr, int *status );
