/*
 * C error define file for facility PRM (1500)
 * Generated by the MESSGEN utility
 */

#ifndef PRM_ERROR_DEFINED
#define PRM_ERROR_DEFINED

/* argument/operand invalid */
enum { PRM__ARGIN           	= 232555296 };	/* messid=100 */

/* floating point divide by zero */
enum { PRM__FLTDZ           	= 232555304 };	/* messid=101 */

/* floating point overflow */
enum { PRM__FLTOF           	= 232555312 };	/* messid=102 */

/* floating point underflow */
enum { PRM__FLTUF           	= 232555320 };	/* messid=103 */

/* integer divide by zero */
enum { PRM__INTDZ           	= 232555328 };	/* messid=104 */

/* integer overflow */
enum { PRM__INTOF           	= 232555336 };	/* messid=105 */

/* logarithm of zero or negative number */
enum { PRM__LOGZN           	= 232555344 };	/* messid=106 */

/* numerical significance lost */
enum { PRM__SLOST           	= 232555352 };	/* messid=107 */

/* square root of negative number */
enum { PRM__SQRNG           	= 232555360 };	/* messid=108 */

/* undefined exponentiation */
enum { PRM__UDEXP           	= 232555368 };	/* messid=109 */

/* floating point error */
enum { PRM__FPERR           	= 232555376 };	/* messid=110 */


#endif	/* PRM_ERROR_DEFINED */
