/*
 * C error define file for facility ARY (1503)
 * Generated by the MESSGEN utility
 */

#ifndef ARY_ERROR_DEFINED
#define ARY_ERROR_DEFINED

/* access type specification invalid */
enum { ARY__ACCIN           	= 232753506 };	/* messid=300 */

/* access denied */
enum { ARY__ACDEN           	= 232753514 };	/* messid=301 */

/* conflicting array access */
enum { ARY__CFLAC           	= 232753522 };	/* messid=302 */

/* dimensions invalid */
enum { ARY__DIMIN           	= 232753530 };	/* messid=303 */

/* Tii many ARY arrays in use at once */
enum { ARY__XSARY           	= 232753538 };	/* messid=304 */

/* fatal internal error */
enum { ARY__FATIN           	= 232753546 };	/* messid=305 */

/* full data type specification invalid */
enum { ARY__FTPIN           	= 232753554 };	/* messid=306 */

/* array identifier invalid */
enum { ARY__IDINV           	= 232753562 };	/* messid=307 */

/* array currently mapped for access */
enum { ARY__ISMAP           	= 232753570 };	/* messid=308 */

/* mapping mode specification invalid */
enum { ARY__MMDIN           	= 232753578 };	/* messid=309 */

/* number of dimensions invalid */
enum { ARY__NDMIN           	= 232753586 };	/* messid=310 */

/* non-standard data component name */
enum { ARY__NSDCN           	= 232753594 };	/* messid=311 */

/* array not mapped for access */
enum { ARY__NTMAP           	= 232753602 };	/* messid=312 */

/* array placeholder invalid */
enum { ARY__PLINV           	= 232753610 };	/* messid=313 */

/* rogue component in array structure */
enum { ARY__ROGUE           	= 232753618 };	/* messid=314 */

/* pixel-shift specification invalid */
enum { ARY__SFTIN           	= 232753626 };	/* messid=315 */

/* character string truncated */
enum { ARY__TRUNC           	= 232753634 };	/* messid=316 */

/* data type invalid */
enum { ARY__TYPIN           	= 232753642 };	/* messid=317 */

/* array data values undefined */
enum { ARY__UNDEF           	= 232753650 };	/* messid=318 */

/* unsupported array storage form */
enum { ARY__USFRM           	= 232753658 };	/* messid=319 */

/* variant value invalid */
enum { ARY__VARIN           	= 232753666 };	/* messid=320 */

/* too many array dimensions */
enum { ARY__XSDIM           	= 232753674 };	/* messid=321 */

/* storage form conversion error */
enum { ARY__FRMCV           	= 232753682 };	/* messid=322 */

/* facility not yet supported */
enum { ARY__NOTSP           	= 232753690 };	/* messid=323 */

/* invalid scaling information in scaled array */
enum { ARY__SCLIN           	= 232753698 };	/* messid=324 */

/* invalid compression information in delta array */
enum { ARY__DLTIN           	= 232753706 };	/* messid=325 */

/* invalid axis index */
enum { ARY__AXINV           	= 232753714 };	/* messid=326 */

/* attempt to change a read-only property of a compressed array */
enum { ARY__CMPAC           	= 232753722 };	/* messid=327 */

/* Object not locked by current thread */
enum { ARY__THREAD          	= 232753730 };	/* messid=328 */

/* Array dimensions exceed limits of the 32 bit API */
enum { ARY__TOOBIG          	= 232753738 };	/* messid=329 */


#endif	/* ARY_ERROR_DEFINED */
