/*
 * C error define file for facility EMS (104)
 * Generated by the MESSGEN utility
 */

#ifndef EMS_ERROR_DEFINED
#define EMS_ERROR_DEFINED

/* Error encountered during message output. */
enum { EMS__OPTER           	= 141067842 };	/* messid=200 */

/* No error messages pending output. */
enum { EMS__NOMSG           	= 141067850 };	/* messid=201 */

/* Status not set in call to EMS_REP (improper use of EMS_REP). */
enum { EMS__UNSET           	= 141068642 };	/* messid=300 */

/* Status set to SAI__OK in call to EMS_REP (improper use of EMS_REP). */
enum { EMS__BADOK           	= 141068650 };	/* messid=301 */

/* Error in nested calls to EMS_BEGIN and EMS_END (improper use of EMS). */
enum { EMS__NSTER           	= 141068658 };	/* messid=302 */

/* Invalid keyword will be ignored (improper use of EMS_TUNE). */
enum { EMS__BDKEY           	= 141068666 };	/* messid=303 */

/* Conflicting actions (improper use of EMS_TUNE). */
enum { EMS__BTUNE           	= 141068674 };	/* messid=304 */

/* Error encountered reading environment variable EMS_TUNE. */
enum { EMS__NOENV           	= 141068682 };	/* messid=305 */

/* Error stack overflow (EMS fault). */
enum { EMS__EROVF           	= 141069442 };	/* messid=400 */

/* Context stack overflow (EMS fault). */
enum { EMS__CXOVF           	= 141069450 };	/* messid=401 */

/* Test facility error check. */
enum { EMS__TEST            	= 141069458 };	/* messid=402 */


#endif	/* EMS_ERROR_DEFINED */
