/*
 * C error define file for facility ERR (102)
 * Generated by the MESSGEN utility
 */

#ifndef ERR_ERROR_DEFINED
#define ERR_ERROR_DEFINED

/* Error encountered during message output. */
enum { ERR__OPTER           	= 140936770 };	/* messid=200 */

/* Status not set in call to ERR_REP (improper use of ERR_REP). */
enum { ERR__UNSET           	= 140937570 };	/* messid=300 */

/* Status set to SAI__OK in call to ERR_REP (improper use of ERR_REP). */
enum { ERR__BADOK           	= 140937578 };	/* messid=301 */

/* Invalid tuning parameter name (improper use of ERR_TUNE). */
enum { ERR__BDPAR           	= 140937586 };	/* messid=302 */

/* Bad tuning value (improper use of ERR_TUNE). */
enum { ERR__BTUNE           	= 140937594 };	/* messid=303 */

/* Bad ERR environment variable value. */
enum { ERR__BDENV           	= 140937602 };	/* messid=304 */


#endif	/* ERR_ERROR_DEFINED */
