/*
 * C error define file for facility ONE (1522)
 * Generated by the MESSGEN utility
 */

#ifndef ONE_ERROR_DEFINED
#define ONE_ERROR_DEFINED

/* No more files */
enum { ONE__NOFILES         	= 233996296 };	/* messid=1 */

/* Pipe Error */
enum { ONE__PIPEERR         	= 233996304 };	/* messid=2 */

/* Name Length Error */
enum { ONE__LENERR          	= 233996312 };	/* messid=3 */

/* Malloc error */
enum { ONE__MALLOCERR       	= 233996320 };	/* messid=4 */

/* Error in exec/fork */
enum { ONE__EXECERROR       	= 233996328 };	/* messid=5 */

/* String truncated */
enum { ONE__TRUNC           	= 233996336 };	/* messid=6 */

/* Format conversion error */
enum { ONE__CNVERR          	= 233996344 };	/* messid=7 */


#endif	/* ONE_ERROR_DEFINED */
