/*
 * C error define file for facility DAT (200)
 * Generated by the MESSGEN utility
 */

#ifndef DAT_ERROR_DEFINED
#define DAT_ERROR_DEFINED

/* Locator invalid */
enum { DAT__LOCIN           	= 147358499 };	/* messid=100 */

/* Locator target erased */
enum { DAT__LOCER           	= 147358507 };	/* messid=101 */

/* Type invalid */
enum { DAT__TYPIN           	= 147358515 };	/* messid=102 */

/* Name invalid */
enum { DAT__NAMIN           	= 147358523 };	/* messid=103 */

/* Mode invalid */
enum { DAT__MODIN           	= 147358531 };	/* messid=104 */

/* Conversion invalid */
enum { DAT__CONIN           	= 147358539 };	/* messid=105 */

/* Deletion invalid */
enum { DAT__DELIN           	= 147358547 };	/* messid=106 */

/* Dimensions invalid */
enum { DAT__DIMIN           	= 147358555 };	/* messid=107 */

/* File invalid */
enum { DAT__FILIN           	= 147358563 };	/* messid=108 */

/* Object invalid */
enum { DAT__OBJIN           	= 147358571 };	/* messid=109 */

/* Group invalid */
enum { DAT__GRPIN           	= 147358579 };	/* messid=110 */

/* Subscripts invalid */
enum { DAT__SUBIN           	= 147358587 };	/* messid=111 */

/* Component already exists */
enum { DAT__COMEX           	= 147358595 };	/* messid=112 */

/* Object not found */
enum { DAT__OBJNF           	= 147358603 };	/* messid=113 */

/* Text truncated */
enum { DAT__TRUNC           	= 147358611 };	/* messid=114 */

/* Access conflict */
enum { DAT__ACCON           	= 147358619 };	/* messid=115 */

/* Conversion error */
enum { DAT__CONER           	= 147358627 };	/* messid=116 */

/* Primitive data undefined */
enum { DAT__UNSET           	= 147358635 };	/* messid=117 */

/* Version mismatch */
enum { DAT__VERMM           	= 147358643 };	/* messid=118 */

/* Primitive data mapped */
enum { DAT__PRMAP           	= 147358651 };	/* messid=119 */

/* Relationship invalid */
enum { DAT__RELIN           	= 147358659 };	/* messid=120 */

/* File locking error */
enum { DAT__FILCK           	= 147358667 };	/* messid=121 */

/* File not found */
enum { DAT__FILNF           	= 147358675 };	/* messid=122 */

/* File protected */
enum { DAT__FILPR           	= 147358683 };	/* messid=123 */

/* Integrity check */
enum { DAT__INCHK           	= 147358691 };	/* messid=124 */

/* Fatal internal error */
enum { DAT__FATAL           	= 147358699 };	/* messid=125 */

/* Unknown error */
enum { DAT__WEIRD           	= 147358707 };	/* messid=126 */

/* Too many data parameters */
enum { DAT__EXCPA           	= 147358715 };	/* messid=127 */

/* Unknown data parameter */
enum { DAT__UNKPA           	= 147358723 };	/* messid=128 */

/* Parameter is currently active */
enum { DAT__ISOPN           	= 147358731 };	/* messid=129 */

/* Error activating DAT */
enum { DAT__ERACT           	= 147358739 };	/* messid=130 */

/* Error establishing DAT exit handler */
enum { DAT__EREXH           	= 147358747 };	/* messid=131 */

/* Not mapped */
enum { DAT__NOMAP           	= 147358755 };	/* messid=132 */

/* Data currently mapped */
enum { DAT__ISMAP           	= 147358763 };	/* messid=133 */

/* Recursion stack overflow */
enum { DAT__STKOF           	= 147358771 };	/* messid=134 */

/* Outside bounds of object */
enum { DAT__BOUND           	= 147358779 };	/* messid=135 */

/* HDS is already active */
enum { DAT__ACTIV           	= 147358787 };	/* messid=136 */

/* File close error */
enum { DAT__FILCL           	= 147358795 };	/* messid=137 */

/* File create error */
enum { DAT__FILCR           	= 147358803 };	/* messid=138 */

/* File mapping error */
enum { DAT__FILMP           	= 147358811 };	/* messid=139 */

/* File not deleted */
enum { DAT__FILND           	= 147358819 };	/* messid=140 */

/* File not extended */
enum { DAT__FILNX           	= 147358827 };	/* messid=141 */

/* File read error */
enum { DAT__FILRD           	= 147358835 };	/* messid=142 */

/* File write error */
enum { DAT__FILWR           	= 147358843 };	/* messid=143 */

/* Memory allocation error */
enum { DAT__NOMEM           	= 147358851 };	/* messid=144 */

/* Wild-card search context invalid */
enum { DAT__WLDIN           	= 147358859 };	/* messid=145 */

/* No component name */
enum { DAT__NOCMP           	= 147358867 };	/* messid=146 */

/* Dimensions truncate in Fortran INTEGER*4 */
enum { DAT__DTRNC           	= 147358875 };	/* messid=147 */


#endif	/* DAT_ERROR_DEFINED */
