#define datAlter datAlter_v4
#define datAnnul datAnnul_v4
#define datBasic datBasic_v4
#define datCcopy datCcopy_v4
#define datCctyp datCctyp_v4
#define datCell datCell_v4
#define datChscn datChscn_v4
#define datClen datClen_v4
#define datClone datClone_v4
#define datCoerc datCoerc_v4
#define datCopy datCopy_v4
#define datDrep datDrep_v4
#define datErase datErase_v4
#define datErmsg datErmsg_v4
#define datFind datFind_v4
#define datGet datGet_v4
#define datGetC datGetC_v4
#define datGetD datGetD_v4
#define datGetI datGetI_v4
#define datGetK datGetK_v4
#define datGetW datGetW_v4
#define datGetUW datGetUW_v4
#define datGetL datGetL_v4
#define datGetR datGetR_v4
#define datGet0C datGet0C_v4
#define datGet0D datGet0D_v4
#define datGet0R datGet0R_v4
#define datGet0I datGet0I_v4
#define datGet0K datGet0K_v4
#define datGet0W datGet0W_v4
#define datGet0UW datGet0UW_v4
#define datGet0L datGet0L_v4
#define datGet1C datGet1C_v4
#define datGet1D datGet1D_v4
#define datGet1I datGet1I_v4
#define datGet1K datGet1K_v4
#define datGet1W datGet1W_v4
#define datGet1UW datGet1UW_v4
#define datGet1R datGet1R_v4
#define datGet1L datGet1L_v4
#define datGetVC datGetVC_v4
#define datGetVD datGetVD_v4
#define datGetVI datGetVI_v4
#define datGetVK datGetVK_v4
#define datGetVR datGetVR_v4
#define datGetVL datGetVL_v4
#define datIndex datIndex_v4
#define datLen datLen_v4
#define datMap datMap_v4
#define datMapC datMapC_v4
#define datMapD datMapD_v4
#define datMapI datMapI_v4
#define datMapK datMapK_v4
#define datMapL datMapL_v4
#define datMapR datMapR_v4
#define datMapN datMapN_v4
#define datMapV datMapV_v4
#define datMould datMould_v4
#define datMove datMove_v4
#define datMsg datMsg_v4
#define datName datName_v4
#define datNcomp datNcomp_v4
#define datNew datNew_v4
#define datNewC datNewC_v4
#define datNew0 datNew0_v4
#define datNew0D datNew0D_v4
#define datNew0I datNew0I_v4
#define datNew0K datNew0K_v4
#define datNew0W datNew0W_v4
#define datNew0UW datNew0UW_v4
#define datNew0R datNew0R_v4
#define datNew0L datNew0L_v4
#define datNew0C datNew0C_v4
#define datNew1 datNew1_v4
#define datNew1C datNew1C_v4
#define datNew1D datNew1D_v4
#define datNew1I datNew1I_v4
#define datNew1K datNew1K_v4
#define datNew1W datNew1W_v4
#define datNew1UW datNew1UW_v4
#define datNew1L datNew1L_v4
#define datNew1R datNew1R_v4
#define datParen datParen_v4
#define datPrec datPrec_v4
#define datPrim datPrim_v4
#define datPrmry datPrmry_v4
#define datPutC datPutC_v4
#define datPutD datPutD_v4
#define datPutI datPutI_v4
#define datPutK datPutK_v4
#define datPutW datPutW_v4
#define datPutUW datPutUW_v4
#define datPutR datPutR_v4
#define datPutL datPutL_v4
#define datPut datPut_v4
#define datPut0C datPut0C_v4
#define datPut0D datPut0D_v4
#define datPut0R datPut0R_v4
#define datPut0I datPut0I_v4
#define datPut0K datPut0K_v4
#define datPut0W datPut0W_v4
#define datPut0UW datPut0UW_v4
#define datPut0L datPut0L_v4
#define datPut1C datPut1C_v4
#define datPut1D datPut1D_v4
#define datPut1I datPut1I_v4
#define datPut1K datPut1K_v4
#define datPut1W datPut1W_v4
#define datPut1UW datPut1UW_v4
#define datPut1R datPut1R_v4
#define datPut1L datPut1L_v4
#define datPutVD datPutVD_v4
#define datPutVI datPutVI_v4
#define datPutVK datPutVK_v4
#define datPutVR datPutVR_v4
#define datPutVL datPutVL_v4
#define datPutVC datPutVC_v4
#define datRef datRef_v4
#define datRefct datRefct_v4
#define datRenam datRenam_v4
#define datReset datReset_v4
#define datRetyp datRetyp_v4
#define datShape datShape_v4
#define datSize datSize_v4
#define datSlice datSlice_v4
#define datState datState_v4
#define datStruc datStruc_v4
#define datTemp datTemp_v4
#define datThere datThere_v4
#define datType datType_v4
#define datUnmap datUnmap_v4
#define datValid datValid_v4
#define datVec datVec_v4
#define hdsCopy hdsCopy_v4
#define hdsErase hdsErase_v4
#define hdsEwild hdsEwild_v4
#define hdsFlush hdsFlush_v4
#define hdsFree hdsFree_v4
#define hdsGroup hdsGroup_v4
#define hdsGtune hdsGtune_v4
#define hdsInfoI hdsInfoI_v4
#define hdsLink hdsLink_v4
#define hdsLock hdsLock_v4
#define hdsNew hdsNew_v4
#define hdsOpen hdsOpen_v4
#define hdsShow hdsShow_v4
#define hdsState hdsState_v4
#define hdsStop hdsStop_v4
#define hdsTrace hdsTrace_v4
#define hdsTune hdsTune_v4
#define hdsWild hdsWild_v4
#define datConv datConv_v4
#define hdsClose hdsClose_v4
#define hdsFind hdsFind_v4
